name: Gradle publish

on:
  workflow_dispatch:
  release:
    types: [ created ]

jobs:
  publish:
    environment:
      name: publish
    strategy:
      matrix:
        os: [ macOS-latest, windows-latest ]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v3.0.0
      - uses: actions/setup-java@v3.0.0
        with:
          java-version: 11
          distribution: liberica
      - name: Cache konan
        uses: actions/cache@v3.0.1
        with:
          path: ~/.konan
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/wrapper-validation-action@v1.0.4
      - name: Publish Windows Artifacts
        if: matrix.os == 'windows-latest'
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: |
            releaseAll
            -Ppublishing.enabled=true
            -Ppublishing.sonatype=false
            -Ppublishing.space.user=${{ secrets.SPACE_APP_ID }}
            -Ppublishing.space.token=${{ secrets.SPACE_APP_SECRET }}
      - name: Publish Mac Artifacts
        if: matrix.os == 'macOS-latest'
        uses: gradle/gradle-build-action@v2.1.5
        with:
          arguments: |
            releaseMacosX64
            releaseIosArm64
            releaseIosX64
            -Ppublishing.enabled=true
            -Ppublishing.sonatype=false            
            -Ppublishing.space.user=${{ secrets.SPACE_APP_ID }}
            -Ppublishing.space.token=${{ secrets.SPACE_APP_SECRET }}
